### ISSUE TITLE
About ReLoRA usage

### ISSUE THREAD

**Issue by haofanwang** [Guitaricet/peft_pretraining#8]
@Guitaricet Hi, great work! I'm interested in using relora in text to image generation but have several questions.

From my understanding, as written in Algorithm 1 of the paper, ReLoRA merges the learned W_{A}, W_{B} into W from the frozen model at each restart, so ReLoRA actually trains a bunch of W_{A} and W_{B}. In comparison, LoRA only trains one W_{A}, W_{B}.

If so, as the W_{A} and W_{B} have already been merged into W (the frozen model gets updated), the ReLoRA weights cannot be made pluggable as LoRA. An alternative way is to save all group of [W_{A}, W_{B}] and load them during inference.

Please correct me if I'm wrong.

**Comment by Guitaricet** [comment]
Hi! Thank you, I'm very glad you liked the paper!

You are correct. One thing that could maybe be improved if you want plug-in weights is to store the matrices $\sum_i W^i_A W^i_B$ instead of a set ${(W^i_A, W^i_B)}_i$. Which one is more effective depends on the hidden size and the lora rank.

Sorry for a long response, feel free to follow-up on your quesiton and I will try to answer as soon as I can!

**Comment by haofanwang** [comment]
Thanks.
